/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.willian.view;

import br.com.willian.Dao.CategoriaDao;
import br.com.willian.Dao.CorDao;
import br.com.willian.Dao.MarcaDao;
import br.com.willian.Dao.ModeloDao;
import br.com.willian.Dao.ProdutoDao;
import br.com.willian.util.Formatacao;
import br.com.willian.controller.ModeloTabelaProdutos;
import br.com.willian.entity.Categoria;
import br.com.willian.entity.Cor;
import br.com.willian.entity.Marca;
import br.com.willian.entity.Modelo;
import br.com.willian.entity.Produto;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Willian
 */
public class TelaCadastroProdutos extends javax.swing.JFrame {
   
    private ModeloDao modDao = new ModeloDao();
    private CorDao cDao = new CorDao();
    private MarcaDao mDao = new MarcaDao();
    private CategoriaDao catDao = new CategoriaDao();
    private ProdutoDao pDao = new ProdutoDao();
    
    /**
     * Creates new form TelaCadastroProdutos
     */
    public TelaCadastroProdutos() {
        
          initComponents();
          btnEditar.setBackground(Color.decode("#6495ED"));
          btnSalvar.setBackground(Color.decode("#32CD32"));
          btnExcluir.setBackground(Color.decode("#FF6347"));
          txtCodProduto.requestFocus();
          populaComboboxMarca();
          populaComboboxModelo();
          populaComboboxCategoria();
          populaComboboxCor();
          preencherTabela();
          limparCampos();
          txtPcusto.setText("0,00");
          txtPvenda.setText("0,00");
          setLocationRelativeTo(null);
                           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxModelo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxCor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxMarca = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxTamanho = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtPcusto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPvenda = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCadastroDesc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtbProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de produtos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro e gerenciamento de produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 24))); // NOI18N

        jLabel2.setText("Código do produto");

        jLabel4.setText("Modelo");

        jLabel5.setText("Cor");

        jLabel3.setText("Marca");

        jLabel6.setText("Categoria");

        jLabel7.setText("Tamanho");

        cbxTamanho.setMaximumRowCount(4);
        cbxTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PP", "P", "M", "G", "GG", "XG", "XXG", "36", "38", "40", "42", "44", "46", "48", "50", "52", " " }));

        jLabel8.setText("Preço de custo R$");

        txtPcusto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPcustoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPcustoFocusLost(evt);
            }
        });

        jLabel9.setText("Preço de venda R$");

        txtPvenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPvendaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPvendaFocusLost(evt);
            }
        });

        jLabel10.setText("Quantidade");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/willian/imagens/icon_salvar.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar Produto");
        btnSalvar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 3, 1, new java.awt.Color(0, 0, 0)));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/willian/imagens/icon_edicao.png"))); // NOI18N
        btnEditar.setToolTipText("Editar Produto");
        btnEditar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 3, 1, new java.awt.Color(0, 0, 0)));
        btnEditar.setName("Editar"); // NOI18N
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/willian/imagens/icon_delete.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir produto");
        btnExcluir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 3, 1, new java.awt.Color(0, 0, 0)));
        btnExcluir.setPreferredSize(new java.awt.Dimension(75, 33));
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirMouseExited(evt);
            }
        });
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar operação");
        btnCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 3, 1, new java.awt.Color(0, 0, 0)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCadastroDesc.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCadastroDesc.setText("Cadastro de Descrição de Produtos");
        btnCadastroDesc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 3, 1, new java.awt.Color(0, 0, 0)));
        btnCadastroDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastroDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPcusto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPcusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastroDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        JtbProdutos.setShowHorizontalLines(false);
        JtbProdutos.setShowVerticalLines(false);
        jScrollPane1.setViewportView(JtbProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
     
          Boolean validacao = validaCampos();
          String acao = null;
          if(validacao == true){
                    if(JtbProdutos.getSelectedRow() != -1){
                              acao = "edit";
                    }else{
                              acao = "cad";
                    } 
                    Produto p = capturaDadosDaTela();  
                    Boolean limparCampos = pDao.salvarProduto(p,acao);
                    if(limparCampos == true){
                              limparCampos();
                              txtPcusto.setText("0,00");
                              txtPvenda.setText("0,00");
                              preencherTabela();
                    }
                
                    txtCodProduto.setEnabled(true);
                 
                
          }
     
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
          if(JtbProdutos.getSelectedRow() != -1){
                    carregarCampos();
          
          } else{
                    JOptionPane.showMessageDialog(null, "Selecione a linha da tabela a baixo que contém" 
                             + " o produto que você deseja editar");
          } 
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
       
          btnEditar.setBackground(Color.decode("#4169E1"));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        
          btnEditar.setBackground(Color.decode("#6495ED"));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
       
          btnSalvar.setBackground(Color.decode("#228B22"));
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
      
          btnSalvar.setBackground(Color.decode("#32CD32"));
    }//GEN-LAST:event_btnSalvarMouseExited
 
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
      
          if(JtbProdutos.getSelectedRow() != -1){
                    String codigoProduto = JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(), 0).toString();
                    int op = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir o produto " + codigoProduto + "?", "Sistema"
                    , JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE
                    , null, new String[]{"Sim","Não","Cancelar"}, "Cancelar");
                   if(op == 0){
                             pDao.deletarProduto(codigoProduto);
                             preencherTabela();
                             txtCodProduto.requestFocus();
                   }
          }else{
                    JOptionPane.showMessageDialog(null, "Selecione a linha da tabela a baixo que contém" 
                    + " o produto que você deseja excluir");
         }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseEntered
         
          btnExcluir.setBackground(Color.decode("#FF0000"));
    }//GEN-LAST:event_btnExcluirMouseEntered

    private void btnExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseExited
          
          btnExcluir.setBackground(Color.decode("#FF6347"));
    }//GEN-LAST:event_btnExcluirMouseExited

    private void txtPcustoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPcustoFocusLost
            
          if(!(txtPcusto.getText().equals(""))){
                    String valor = txtPcusto.getText();
                    String preco_custo = Formatacao.mascaraTxtMonetario(valor);
                   txtPcusto.setText(preco_custo);
          }
    }//GEN-LAST:event_txtPcustoFocusLost

    private void txtPvendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPvendaFocusLost
       
          if(!(txtPvenda.getText().equals(""))){
                    String valorDeVenda = Formatacao.mascaraTxtMonetario(txtPvenda.getText());
                    txtPvenda.setText(valorDeVenda);
         }
    }//GEN-LAST:event_txtPvendaFocusLost

    private void txtPcustoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPcustoFocusGained
         
          txtPcusto.setSelectionStart(0);
          txtPcusto.setSelectionEnd(txtPcusto.getText().length());
    }//GEN-LAST:event_txtPcustoFocusGained

    private void txtPvendaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPvendaFocusGained
        
        txtPvenda.setSelectionStart(0);
          txtPvenda.setSelectionEnd(txtPvenda.getText().length());
    }//GEN-LAST:event_txtPvendaFocusGained

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
        limparCampos();
          txtCodProduto.requestFocus();
          txtPcusto.setText("0,00");
          txtPvenda.setText("0,00");
          txtCodProduto.setEnabled(true);
          JtbProdutos.getSelectionModel().clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastroDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroDescActionPerformed
          TelaCadastroDescricaoDeProdutos telaDesc = new TelaCadastroDescricaoDeProdutos();
          telaDesc.setVisible(true);
          this.dispose();
          
        
    }//GEN-LAST:event_btnCadastroDescActionPerformed
 
    /**
    * 
    * @return Boolean.
    * Método que verifica se os campos foram preenchidos para realizar a persistência
    * dos dados no banco.
    * Se todos os campos estiverem preenchidos retorna true, senão retorna false.
    */
    public Boolean validaCampos(){
        
          Boolean valida = true;
          if(txtCodProduto.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "O Campo Código do produto está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false; 
                    txtCodProduto.requestFocus();
                    return valida;
          }
        
          if(cbxModelo.getSelectedIndex() == -1){
                    JOptionPane.showMessageDialog(null, "O Campo Modelo está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false; 
                    cbxModelo.requestFocus();
                    return valida;
          }
        
          if(cbxCor.getSelectedIndex() == -1){
                    JOptionPane.showMessageDialog(null, "O Campo Cor está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false;
                    cbxCor.requestFocus();
                    return valida;
          }
        
          if(cbxMarca.getSelectedIndex() == -1){
                    JOptionPane.showMessageDialog(null, "O Campo Marca está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false; 
                    cbxMarca.requestFocus();
                    return valida;
          }
        
          if(cbxCategoria.getSelectedIndex() == -1){
                    JOptionPane.showMessageDialog(null, "O Campo Categoria está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false;  
                    cbxCategoria.requestFocus();
                    return valida;
          }
        
          if(cbxTamanho.getSelectedIndex() == -1){
                    JOptionPane.showMessageDialog(null, "O Campo Tamanho está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false; 
                    cbxTamanho.requestFocus();
                    return valida;
          }
        
          if(txtPcusto.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "O Campo Preço de custo está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false;
                    txtPcusto.requestFocus();
                    return valida;
          }
        
          if(txtPvenda.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "O Campo Preço de venda está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false;
                    txtPvenda.requestFocus();
                    return valida;
          }
        
          if(txtQtd.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "O Campo Quantidade está em branco! \n" 
                    + " Favor preencha o campo para salvar o produto.");
                    valida = false;
                    txtQtd.requestFocus();
                    return valida;
          }
          String str = txtPcusto.getText();
          Boolean retornotxtPcusto = Formatacao.verificaSeTemApenasNumeros(str);
          if(retornotxtPcusto == false){
                    txtPcusto.setText("0,00");
                    txtPcusto.requestFocus();
                    return retornotxtPcusto;
          }
         
          String str2 = txtPvenda.getText();
          Boolean retornotxtPvenda = Formatacao.verificaSeTemApenasNumeros(str2);
          if(retornotxtPvenda == false){
                    txtPvenda.setText("0,00");
                    txtPvenda.requestFocus();
             
                    return retornotxtPvenda;
          }
          return valida;
    }
    
    /**
      * @return Um objeto Produto.
     * Método que captura todos os dados dos campos da tela, instancia um objeto Produto, atribui os dados capturados
     *aos atributos de Produto e retorna o mesmo. 
     */
    public Produto capturaDadosDaTela(){
        
          String cod_produto = txtCodProduto.getText().toUpperCase();
          Modelo mod  = modDao.buscarPorNome(cbxModelo.getSelectedItem().toString());
          Cor c = cDao.buscarPorNome(cbxCor.getSelectedItem().toString());
          Marca m = mDao.buscarPorNome(cbxMarca.getSelectedItem().toString());
          Categoria cat  = catDao.buscarPorNome(cbxCategoria.getSelectedItem().toString());
          String preco_custo = Formatacao.formataValorMonetarioParabanco(txtPcusto.getText());   
          String preco_venda = Formatacao.formataValorMonetarioParabanco(txtPvenda.getText());
          String tamanho = cbxTamanho.getSelectedItem().toString();
          String qtd = txtQtd.getText();
          Produto p = new Produto(cod_produto, m, mod, tamanho, c, cat,
                    new BigDecimal(preco_custo), new BigDecimal(preco_venda), BigDecimal.ZERO, 
                    BigDecimal.ZERO,Integer.parseInt(qtd));
        
          p.setLucro_liquido(p.calculaLucro(p.getPreco_venda(), p.getPreco_custo()));
          p.setMargemLucro_liquido(p.calculaMargem(p.getLucro_liquido(), p.getPreco_custo()));
          return p;
}
    
    /**
     * 
     * @param obj1
     * @param obj2
     * @param obj3
     * @param obj4
     * @param obj5
     * 
     * Método que recebe 5 Objects como parâmetros, percorre todos os JCombobox da tela e compara 
     * cada Object com o valor de cada índice do seu respectivo JCombobox e, através dessa comparação
     * seleciona o índice dos JCombobox conforme os valores das colunas da linha 
     * selecionada na JTable JtbProdutos.
     */
    public void atualizaComboBoxs(Object obj1,Object obj2,Object obj3,Object obj4,Object obj5){
       
          if(JtbProdutos.getSelectedRow() != -1){
                    for(int i =0; i < cbxMarca.getItemCount();i++){
                              if(obj1.equals(cbxMarca.getItemAt(i))){
                                        cbxMarca.setSelectedIndex(i);
                                        break;
                              }
                    }
            
                    for(int i = 0; i < cbxCategoria.getItemCount();i++){
                              if(obj4.equals(cbxCategoria.getItemAt(i))){
                                        cbxCategoria.setSelectedIndex(i);
                                        break;
                              }
                    }
            
                    for(int i = 0;i < cbxCor.getItemCount();i++){
                              if(obj3.equals(cbxCor.getItemAt(i))){
                                        cbxCor.setSelectedIndex(i);
                                        break;
                              }
                    }
            
                    for(int i = 0; i < cbxModelo.getItemCount();i++){
                              if(obj2.equals(cbxModelo.getItemAt(i))){
                                        cbxModelo.setSelectedIndex(i);
                                        break;
                              }
                    }
           
                    for(int i = 0; i < cbxTamanho.getItemCount();i++){
                              if(obj5.equals(cbxTamanho.getItemAt(i))){
                                        cbxTamanho.setSelectedIndex(i);
                                        break;
                              }
                    }
          }
      
    }
   
   /***
    * Método que pega os dados das colunas da linha selecionada da tabela JtbProdutos
    * e carrega nos campos da tela.
   */
    public void carregarCampos(){
        
          if(JtbProdutos.getSelectedRow() != -1){
                    txtCodProduto.setEnabled(false);
                    txtCodProduto.setText(JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(),0).toString());
                    String marcaSelec = JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(), 1).toString();
                    String modeloSelec = JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(), 2).toString();
                    String corSelec = JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(),3).toString();
                    String categoriaSelec = JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(), 4).toString();
                    String tamanhoSelc = JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(),5).toString();
                    
                    atualizaComboBoxs(marcaSelec, modeloSelec, corSelec, categoriaSelec, tamanhoSelc);
                    
                    txtPcusto.setText(JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(),6).toString());
                    txtPvenda.setText(JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(),7).toString());
                    txtQtd.setText(JtbProdutos.getValueAt(JtbProdutos.getSelectedRow(),10).toString());
                   
                   
          }
    }
    
    public void preencherTabela(){
          ArrayList dados = new ProdutoDao().buscaParaPreencherTabela();
          String[] colunas = {"Código do produto","Marca","Modelo","Cor","Categoria","Tamanho"
                    ,"Preço de custo R$","Preço de venda R$","Lucro líquido R$","Margem de lucro líquido %","Qtd"};
          ModeloTabelaProdutos modelo = new ModeloTabelaProdutos(dados, colunas);
       
          JtbProdutos.setModel(modelo);
       
          JtbProdutos.getColumnModel().getColumn(0).setPreferredWidth(120);
          JtbProdutos.getColumnModel().getColumn(0).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(1).setPreferredWidth(200);
          JtbProdutos.getColumnModel().getColumn(1).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(2).setPreferredWidth(120);
          JtbProdutos.getColumnModel().getColumn(2).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(3).setPreferredWidth(90);
          JtbProdutos.getColumnModel().getColumn(3).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(4).setPreferredWidth(200);
          JtbProdutos.getColumnModel().getColumn(4).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(5).setPreferredWidth(70);
          JtbProdutos.getColumnModel().getColumn(5).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(6).setPreferredWidth(120);
          JtbProdutos.getColumnModel().getColumn(6).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(7).setPreferredWidth(120);
          JtbProdutos.getColumnModel().getColumn(7).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(8).setPreferredWidth(120);
          JtbProdutos.getColumnModel().getColumn(8).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(9).setPreferredWidth(170);
          JtbProdutos.getColumnModel().getColumn(9).setResizable(false);
          JtbProdutos.getColumnModel().getColumn(10).setPreferredWidth(40);
          JtbProdutos.getColumnModel().getColumn(10).setResizable(false);       
      
          JtbProdutos.getTableHeader().setReorderingAllowed(false);
          JtbProdutos.setAutoResizeMode(0);
          JtbProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    
    public void populaComboboxMarca(){
        
          MarcaDao mDao = new MarcaDao();
        
          List<Marca> lista = mDao.buscarTodos();
          if(lista != null){
                    for(Marca m : lista){
                              cbxMarca.addItem(m.getNome());
                    }
          }
   }
    
    public void populaComboboxModelo(){
        
          ModeloDao modDao = new ModeloDao();
        
          List<Modelo> lista = modDao.buscarTodos();
        
          if(lista != null){
                    for(Modelo mod : lista){
                              cbxModelo.addItem(mod.getNome());
                    }
          }
        
    }
    
    public void populaComboboxCategoria(){
        
          CategoriaDao catDao = new CategoriaDao();
        
          List<Categoria> lista = catDao.buscarTodos();
        
          if(lista != null){
                    for(Categoria cat : lista){
                              cbxCategoria.addItem(cat.getNome());
                    }
          }
    }
    
    public void populaComboboxCor(){
        
          CorDao cDao = new CorDao();
        
          List<Cor> lista = cDao.buscarTodos();
        
          if(lista != null){
                    for(Cor c : lista){
                              cbxCor.addItem(c.getNome());
                    }
        }
    }
    
    public void limparCampos(){
        
          txtCodProduto.setText("");
          cbxModelo.setSelectedIndex(-1);
          cbxCor.setSelectedIndex(-1);
          cbxMarca.setSelectedIndex(-1);
          cbxCategoria.setSelectedIndex(-1);
          cbxTamanho.setSelectedIndex(-1);
          txtPcusto.setText("0,00");
          txtPvenda.setText("0,00");
          txtQtd.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                    new TelaCadastroProdutos().setVisible(true);
                    }
          });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtbProdutos;
    private javax.swing.JButton btnCadastroDesc;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxCor;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JComboBox<String> cbxModelo;
    private javax.swing.JComboBox<String> cbxTamanho;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtPcusto;
    private javax.swing.JTextField txtPvenda;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
